### ISSUE TITLE
where is the source code of the site: http://ctrl-c.club/~philips/?

### ISSUE THREAD

**Issue by luckypoem** [felipetavares/bake#6]
hi.

u said "You can see an example blog that uses Bake here. Another in here."but where is the source code of the site: http://ctrl-c.club/~philips/?
can u publish it on github.com?

**Comment by felipetavares** [comment]
There you go: [blog.zip](https://github.com/felipetavares/bake/files/554392/blog.zip).

I put there:
- the bakefile;
- the posts;
- the html template;

The css/js files are here: [css.zip](https://github.com/felipetavares/bake/files/554407/css.zip).

**Comment by luckypoem** [comment]
Hi
I ran bake in blog dir,but the index.html  isn't generated ,why?

**Comment by felipetavares** [comment]
If you look at the `bakefile`, you'll notice it has a line with `output=` and a path after that. The path is the path that will be used to write the index.html. For this specific bakefile, I put there the correct path for the ctrl-c.club server, which is of course incorrect for your setup. You need to replace this path with the correct one for your setup, probably just putting `output=index.html` is the best solution for you.

**Comment by luckypoem** [comment]
i setup a blog here: http://cccp.bright.biz.st, and i moved the contents of unzipped css.zip to blog dir,but when i visit http://cccp.bright.biz.st ,the site's appearance is not like yours,so the css files doesn't take effect??

**Comment by felipetavares** [comment]
The contents of css.zip should be in a `css` folder. This is from your generated `index.html` file (which is generated from the template):

```
@import url(css/blog.css);
@import url(css/prism.css);
```

You can also modify the template to not need the css folder.

**Comment by luckypoem** [comment]
now it's ok.thanks
