### ISSUE TITLE
Should smartypants be working?

### ISSUE THREAD

**Issue by bixfrankonis** [felipetavares/bake#8]
Disclaimer: I am not a programmer. I might need an answer in "captain dummy talk". I did even try recompiling after switching out the included sundown sources for the sources directly from the sundown repository but that didn't work either. Am I missing something obvious? Something non-obvious? Thanks.

**Comment by felipetavares** [comment]
It needs some implementation, but it seems to be a relatively straightforward change in this function:

https://github.com/felipetavares/bake/blob/e9573fab6a4d2693131b29c8b398afc4a2f0a3b1/bake.cpp#L187

Basically, smartypants support from sundown needs to be coded in to bake.

I'll do it tomorrow night.

**Comment by felipetavares** [comment]
@bixgit done. Should work out of the box with the current master.
